language: php

php:
  - 5.3

evn:
  - SYMFONY_VERSION=origin/master

before_script:
  - ./bin/ci/install_extensions.sh
  - php vendor/vendors.php

notifications:
  email:
    - leszek.prabucki@gmail.com
